export const housesData = [
    {
        id: 1,
        type: "House",
        name: "House 1",
        description:
            "Real estate is property consisting of land and the buildings on it, along with its natural resources such as crops, minerals or water; immovable property of this nature; an interest vested in this an item of real property, buildings or housing in general.",
        image: "../assets/img/houses/house1.png",
        imageLg: "../assets/img/houses/house1lg.png",
        country: "Indore",
        address: "115, Sanghvi Residency",
        bedrooms: "6",
        bathrooms: "3",
        surface: "4200 sq ft",
        year: "2016",
        price: "110000",
        agent: {
            image: "../assets/img/agents/agent.png",
            name: "Vijayant Joshi",
            phone: "0123 456 78910",
        },
    },
    {
        id: 2,
        type: "House",
        name: "House 2",
        description:
            "Real estate is property consisting of land and the buildings on it, along with its natural resources such as crops, minerals or water; immovable property of this nature; an interest vested in this an item of real property, buildings or housing in general.",
        image: "../assets/img/houses/house2.png",
        imageLg: "../assets/img/houses/house2lg.png",
        country: "Agar (Malwa)",
        address: "239, Vivekanand Nagar Master Colony",
        bedrooms: "6",
        bathrooms: "3",
        surface: "4200 sq ft",
        year: "2016",
        price: "140000",
        agent: {
            image: "../assets/img/agents/agent.png",
            name: "Vijayant Joshi",
            phone: "0123 456 78910",
        },
    },
    {
        id: 3,
        type: "House",
        name: "House 3",
        description:
            "Real estate is property consisting of land and the buildings on it, along with its natural resources such as crops, minerals or water; immovable property of this nature; an interest vested in this an item of real property, buildings or housing in general.",
        image: "../assets/img/houses/house3.png",
        imageLg: "../assets/img/houses/house3lg.png",
        country: "Indore",
        address: "125, Sanghvi Residency",
        bedrooms: "6",
        bathrooms: "3",
        surface: "4200 sq ft",
        year: "2016",
        price: "170000",
        agent: {
            image: "../assets/img/agents/agent.png",
            name: "Vijayant Joshi",
            phone: "0123 456 78910",
        },
    },
    {
        id: 4,
        type: "House",
        name: "House 4",
        description:
            "Real estate is property consisting of land and the buildings on it, along with its natural resources such as crops, minerals or water; immovable property of this nature; an interest vested in this an item of real property, buildings or housing in general.",
        image: "../assets/img/houses/house4.png",
        imageLg: "../assets/img/houses/house4lg.png",
        country: "Agar (Malwa)",
        address: "249, Vivekanand Nagar Master Colony",
        bedrooms: "6",
        bathrooms: "3",
        surface: "4200 sq ft",
        year: "2016",
        price: "200000",
        agent: {
            image: "../assets/img/agents/agent.png",
            name: "Vijayant Joshi",
            phone: "0123 456 78910",
        },
    },
    {
        id: 5,
        type: "House",
        name: "House 5",
        description:
            "Real estate is property consisting of land and the buildings on it, along with its natural resources such as crops, minerals or water; immovable property of this nature; an interest vested in this an item of real property, buildings or housing in general.",
        image: "../assets/img/houses/house5.png",
        imageLg: "../assets/img/houses/house5lg.png",
        country: "Indore",
        address: "135, Sanghvi Residency",
        bedrooms: "5",
        bathrooms: "3",
        surface: "4200 sq ft",
        year: "2015",
        price: "210000",
        agent: {
            image: "../assets/img/agents/agent.png",
            name: "Vijayant Joshi",
            phone: "0123 456 78910",
        },
    },
    {
        id: 6,
        type: "House",
        name: "House 6",
        description:
            "Real estate is property consisting of land and the buildings on it, along with its natural resources such as crops, minerals or water; immovable property of this nature; an interest vested in this an item of real property, buildings or housing in general.",
        image: "../assets/img/houses/house6.png",
        imageLg: "../assets/img/houses/house6lg.png",
        country: "Agar (Malwa)",
        address: "259, Vivekanand Nagar Master Colony",
        bedrooms: "6",
        bathrooms: "3",
        surface: "6200 sq ft",
        year: "2014",
        price: "220000",
        agent: {
            image: "../assets/img/agents/agent.png",
            name: "Vijayant Joshi",
            phone: "0123 456 78910",
        },
    },
    {
        id: 7,
        type: "Apartament",
        name: "Apartament 1",
        description:
            "Real estate is property consisting of land and the buildings on it, along with its natural resources such as crops, minerals or water; immovable property of this nature; an interest vested in this an item of real property, buildings or housing in general.",
        image: "../assets/img/apartments/a1.png",
        imageLg: "../assets/img/apartments/a1lg.png",
        country: "Agar (Malwa)",
        address: "279, Vivekanand Nagar Master Colony",
        bedrooms: "2",
        bathrooms: "1",
        surface: "1200 sq ft",
        year: "2012",
        price: "20000",
        agent: {
            image: "../assets/img/agents/agent.png",
            name: "Vijayant Joshi",
            phone: "0123 456 78910",
        },
    },
    {
        id: 8,
        type: "Apartament",
        name: "Apartament 2",
        description:
            "Real estate is property consisting of land and the buildings on it, along with its natural resources such as crops, minerals or water; immovable property of this nature; an interest vested in this an item of real property, buildings or housing in general.",
        image: "../assets/img/apartments/a2.png",
        imageLg: "../assets/img/apartments/a2lg.png",
        country: "Indore",
        address: "145, Sanghvi Residency",
        bedrooms: "3",
        bathrooms: "1",
        surface: "1000 sq ft",
        year: "2011",
        price: "30000",
        agent: {
            image: "../assets/img/agents/agent.png",
            name: "Vijayant Joshi",
            phone: "0123 456 78910",
        },
    },
    {
        id: 9,
        type: "Apartament",
        name: "Apartament 3",
        description:
            "Real estate is property consisting of land and the buildings on it, along with its natural resources such as crops, minerals or water; immovable property of this nature; an interest vested in this an item of real property, buildings or housing in general.",
        image: "../assets/img/apartments/a3.png",
        imageLg: "../assets/img/apartments/a3lg.png",
        country: "Indore",
        address: "155, Sanghvi Residency",
        bedrooms: "2",
        bathrooms: "1",
        surface: "1100 sq ft",
        year: "2011",
        price: "40000",
        agent: {
            image: "../assets/img/agents/agent.png",
            name: "Vijayant Joshi",
            phone: "0123 456 78910",
        },
    },
    {
        id: 10,
        type: "House",
        name: "House 7",
        description:
            "Real estate is property consisting of land and the buildings on it, along with its natural resources such as crops, minerals or water; immovable property of this nature; an interest vested in this an item of real property, buildings or housing in general.",
        image: "../assets/img/houses/house7.png",
        imageLg: "../assets/img/houses/house7lg.png",
        country: "Agar (Malwa)",
        address: "289, Vivekanand Nagar Master Colony",
        bedrooms: "5",
        bathrooms: "3",
        surface: "3200 sq ft",
        year: "2015",
        price: "117000",
        agent: {
            image: "../assets/img/agents/agent.png",
            name: "Vijayant Joshi",
            phone: "0123 456 78910",
        },
    },
    {
        id: 11,
        type: "House",
        name: "House 8",
        description:
            "Real estate is property consisting of land and the buildings on it, along with its natural resources such as crops, minerals or water; immovable property of this nature; an interest vested in this an item of real property, buildings or housing in general.",
        image: "../assets/img/houses/house8.png",
        imageLg: "../assets/img/houses/house8lg.png",
        country: "Agar (Malwa)",
        address: "219, Vivekanand Nagar Master Colony",
        bedrooms: "7",
        bathrooms: "2",
        surface: "2200 sq ft",
        year: "2019",
        price: "145000",
        agent: {
            image: "../assets/img/agents/agent.png",
            name: "Vijayant Joshi",
            phone: "0123 456 78910",
        },
    },
    {
        id: 12,
        type: "House",
        name: "House 9",
        description:
            "Real estate is property consisting of land and the buildings on it, along with its natural resources such as crops, minerals or water; immovable property of this nature; an interest vested in this an item of real property, buildings or housing in general.",
        image: "../assets/img/houses/house9.png",
        imageLg: "../assets/img/houses/house9lg.png",
        country: "Indore",
        address: "165, Sanghvi Residency",
        bedrooms: "4",
        bathrooms: "4",
        surface: "4600 sq ft",
        year: "2015",
        price: "139000",
        agent: {
            image: "../assets/img/agents/agent.png",
            name: "Vijayant Joshi",
            phone: "0123 456 78910",
        },
    },
    {
        id: 13,
        type: "House",
        name: "House 10",
        description:
            "Real estate is property consisting of land and the buildings on it, along with its natural resources such as crops, minerals or water; immovable property of this nature; an interest vested in this an item of real property, buildings or housing in general.",
        image: "../assets/img/houses/house10.png",
        imageLg: "../assets/img/houses/house10lg.png",
        country: "Agar (Malwa)",
        address: "209, Vivekanand Nagar Master Colony",
        bedrooms: "5",
        bathrooms: "2",
        surface: "5200 sq ft",
        year: "2014",
        price: "180000",
        agent: {
            image: "../assets/img/agents/agent.png",
            name: "Vijayant Joshi",
            phone: "0123 456 78910",
        },
    },
    {
        id: 14,
        type: "House",
        name: "House 11",
        description:
            "Real estate is property consisting of land and the buildings on it, along with its natural resources such as crops, minerals or water; immovable property of this nature; an interest vested in this an item of real property, buildings or housing in general.",
        image: "../assets/img/houses/house11.png",
        imageLg: "../assets/img/houses/house11lg.png",
        country: "Indore",
        address: "175, Sanghvi Residency",
        bedrooms: "5",
        bathrooms: "2",
        surface: "3200 sq ft",
        year: "2011",
        price: "213000",
        agent: {
            image: "../assets/img/agents/agent.png",
            name: "Vijayant Joshi",
            phone: "0123 456 78910",
        },
    },
    {
        id: 15,
        type: "House",
        name: "House 12",
        description:
            "Real estate is property consisting of land and the buildings on it, along with its natural resources such as crops, minerals or water; immovable property of this nature; an interest vested in this an item of real property, buildings or housing in general.",
        image: "../assets/img/houses/house12.png",
        imageLg: "../assets/img/houses/house12lg.png",
        country: "Agar (Malwa)",
        address: "229, Vivekanand Nagar Master Colony",
        bedrooms: "4",
        bathrooms: "3",
        surface: "5200 sq ft",
        year: "2013",
        price: "221000",
        agent: {
            image: "../assets/img/agents/agent.png",
            name: "Vijayant Joshi",
            phone: "0123 456 78910",
        },
    },
    {
        id: 16,
        type: "Apartament",
        name: "Apartament 16",
        description:
            "Real estate is property consisting of land and the buildings on it, along with its natural resources such as crops, minerals or water; immovable property of this nature; an interest vested in this an item of real property, buildings or housing in general.",
        image: "../assets/img/apartments/a4.png",
        imageLg: "../assets/img/apartments/a4lg.png",
        country: "Agar (Malwa)",
        address: "269, Vivekanand Nagar Master Colony",
        bedrooms: "2",
        bathrooms: "1",
        surface: "1300 sq ft",
        year: "2011",
        price: "21000",
        agent: {
            image: "../assets/img/agents/agent.png",
            name: "Vijayant Joshi",
            phone: "0123 456 78910",
        },
    },
    {
        id: 17,
        type: "Apartament",
        name: "Apartament 17",
        description:
            "Real estate is property consisting of land and the buildings on it, along with its natural resources such as crops, minerals or water; immovable property of this nature; an interest vested in this an item of real property, buildings or housing in general.",
        image: "../assets/img/apartments/a5.png",
        imageLg: "../assets/img/apartments/a5lg.png",
        country: "Indore",
        address: "185, Sanghvi Residency",
        bedrooms: "3",
        bathrooms: "1",
        surface: "1000 sq ft",
        year: "2012",
        price: "32000",
        agent: {
            image: "../assets/img/agents/agent.png",
            name: "Vijayant Joshi",
            phone: "0123 456 78910",
        },
    },
    {
        id: 18,
        type: "Apartament",
        name: "Apartament 18",
        description:
            "Real estate is property consisting of land and the buildings on it, along with its natural resources such as crops, minerals or water; immovable property of this nature; an interest vested in this an item of real property, buildings or housing in general.",
        image: "../assets/img/apartments/a6.png",
        imageLg: "../assets/img/apartments/a6lg.png",
        country: "Agar (Malwa)",
        address: "299, Vivekanand Nagar Master Colony",
        bedrooms: "3",
        bathrooms: "1",
        surface: "1200 sq ft",
        year: "2010",
        price: "38000",
        agent: {
            image: "../assets/img/agents/agent.png",
            name: "Vijayant Joshi",
            phone: "0123 456 78910",
        },
    },
];